# Generated by Django 3.0.5 on 2020-06-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, default=20.0, help_text='Default is 20$', max_digits=8, verbose_name='price')),
                ('preparation_time', models.PositiveIntegerField(default=5, help_text='Counted in minutes, default is 5', verbose_name='preparation time')),
                ('is_vegan', models.BooleanField(default=False, verbose_name='is vegan')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('dishes', models.ManyToManyField(related_name='cards', to='cards.Dish')),
            ],
        ),
    ]
